// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18444
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace PointOfSales.Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class AddSalesCombinationToOrderFeature : Xunit.IUseFixture<AddSalesCombinationToOrderFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "AddSalesCombinationToOrder.feature"
#line hidden
        
        public AddSalesCombinationToOrderFeature()
        {
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Add sales combination to order", "In order to quickly fill order with products on sale\nAs a salesman\nI want to be a" +
                    "ble to add a sales combination to an order", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Price"});
            table1.AddRow(new string[] {
                        "Apple iPhone 5",
                        "500"});
            table1.AddRow(new string[] {
                        "Belkin Charge",
                        "50"});
            table1.AddRow(new string[] {
                        "Speck SmartFlex Case",
                        "100"});
#line 7
 testRunner.Given("there are following products in shop", ((string)(null)), table1, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "MainProduct",
                        "SubProduct",
                        "Discount"});
            table2.AddRow(new string[] {
                        "Apple iPhone 5",
                        "Belkin Charge",
                        "5"});
            table2.AddRow(new string[] {
                        "Apple iPhone 5",
                        "Speck SmartFlex Case",
                        "20"});
#line 12
 testRunner.And("there are following sales combinations in shop", ((string)(null)), table2, "And ");
#line hidden
        }
        
        public virtual void SetFixture(AddSalesCombinationToOrderFeature.FixtureData fixtureData)
        {
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Add sales combination to order")]
        [Xunit.TraitAttribute("Description", "Adding sales combination with new products adds both products and applies discoun" +
            "t")]
        public virtual void AddingSalesCombinationWithNewProductsAddsBothProductsAndAppliesDiscount()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Adding sales combination with new products adds both products and applies discoun" +
                    "t", ((string[])(null)));
#line 17
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 18
 testRunner.Given("I have an empty order", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "MainProduct",
                        "SubProduct"});
            table3.AddRow(new string[] {
                        "Apple iPhone 5",
                        "Belkin Charge"});
#line 19
 testRunner.When("I add following sales combination to this order", ((string)(null)), table3, "When ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "ProductName",
                        "Quantity"});
            table4.AddRow(new string[] {
                        "Apple iPhone 5",
                        "1"});
            table4.AddRow(new string[] {
                        "Belkin Charge",
                        "1"});
#line 22
 testRunner.Then("order should have following lines", ((string)(null)), table4, "Then ");
#line 26
  testRunner.And("total price should be 545", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Add sales combination to order")]
        [Xunit.TraitAttribute("Description", "Adding sales combination for already added product increases product quantity and" +
            " adds second product with discount")]
        public virtual void AddingSalesCombinationForAlreadyAddedProductIncreasesProductQuantityAndAddsSecondProductWithDiscount()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Adding sales combination for already added product increases product quantity and" +
                    " adds second product with discount", ((string[])(null)));
#line 28
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 29
 testRunner.Given("I have an empty order", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 30
 testRunner.When("I add \'Apple iPhone 5\' to this order", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "MainProduct",
                        "SubProduct"});
            table5.AddRow(new string[] {
                        "Apple iPhone 5",
                        "Belkin Charge"});
#line 31
  testRunner.And("I add following sales combination to this order", ((string)(null)), table5, "And ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "ProductName",
                        "Quantity"});
            table6.AddRow(new string[] {
                        "Apple iPhone 5",
                        "2"});
            table6.AddRow(new string[] {
                        "Belkin Charge",
                        "1"});
#line 34
 testRunner.Then("order should have following lines", ((string)(null)), table6, "Then ");
#line 38
   testRunner.And("total price should be 1045", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Add sales combination to order")]
        [Xunit.TraitAttribute("Description", "Adding two products from sales combination automatically applies discount")]
        public virtual void AddingTwoProductsFromSalesCombinationAutomaticallyAppliesDiscount()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Adding two products from sales combination automatically applies discount", ((string[])(null)));
#line 40
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 41
 testRunner.Given("I have an empty order", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 42
 testRunner.When("I add \'Apple iPhone 5\' to this order", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 43
 testRunner.And("I add \'Belkin Charge\' to this order", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "ProductName",
                        "Quantity"});
            table7.AddRow(new string[] {
                        "Apple iPhone 5",
                        "1"});
            table7.AddRow(new string[] {
                        "Belkin Charge",
                        "1"});
#line 44
 testRunner.Then("order should have following lines", ((string)(null)), table7, "Then ");
#line 48
  testRunner.And("total price should be 545", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Add sales combination to order")]
        [Xunit.TraitAttribute("Description", "Adding sales combination for already added products increases both quantities and" +
            " applies discount")]
        public virtual void AddingSalesCombinationForAlreadyAddedProductsIncreasesBothQuantitiesAndAppliesDiscount()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Adding sales combination for already added products increases both quantities and" +
                    " applies discount", ((string[])(null)));
#line 50
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 51
 testRunner.Given("I have an empty order", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 52
 testRunner.When("I add \'Apple iPhone 5\' to this order", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 53
 testRunner.And("I add \'Belkin Charge\' to this order", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "MainProduct",
                        "SubProduct"});
            table8.AddRow(new string[] {
                        "Apple iPhone 5",
                        "Belkin Charge"});
#line 54
 testRunner.And("I add following sales combination to this order", ((string)(null)), table8, "And ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "ProductName",
                        "Quantity"});
            table9.AddRow(new string[] {
                        "Apple iPhone 5",
                        "2"});
            table9.AddRow(new string[] {
                        "Belkin Charge",
                        "2"});
#line 57
 testRunner.Then("order should have following lines", ((string)(null)), table9, "Then ");
#line 61
  testRunner.And("total price should be 1090", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                AddSalesCombinationToOrderFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                AddSalesCombinationToOrderFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
